### ISSUE TITLE
Some tests failing on Ubuntu install.

### ISSUE THREAD

**Issue by Jakobovski** [enthought/pyql#110]
Hi,

I installed pyql according to the instructions on a Ubuntu machine. Nearly all of the tests passed except for a few. See below.

Any ideas on how I can fix this?

Thanks!

```
=====================================================================
ERROR: test_at (quantlib.test.test_schedule.ScheduleMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/pyql/quantlib/test/test_schedule.py", line 49, in setUp
    self.convention, self.termination_convention, self.rule
  File "quantlib/time/schedule.pyx", line 49, in quantlib.time.schedule.Schedule.__init__ (quantlib/time/schedule.cpp:1740)
    self._thisptr = new _schedule.Schedule(
RuntimeError: undecidable comparison between 4W and 1M

======================================================================
ERROR: test_dates (quantlib.test.test_schedule.ScheduleMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/pyql/quantlib/test/test_schedule.py", line 49, in setUp
    self.convention, self.termination_convention, self.rule
  File "quantlib/time/schedule.pyx", line 49, in quantlib.time.schedule.Schedule.__init__ (quantlib/time/schedule.cpp:1740)
    self._thisptr = new _schedule.Schedule(
RuntimeError: undecidable comparison between 4W and 1M

======================================================================
ERROR: test_iter_dates (quantlib.test.test_schedule.ScheduleMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/pyql/quantlib/test/test_schedule.py", line 49, in setUp
    self.convention, self.termination_convention, self.rule
  File "quantlib/time/schedule.pyx", line 49, in quantlib.time.schedule.Schedule.__init__ (quantlib/time/schedule.cpp:1740)
    self._thisptr = new _schedule.Schedule(
RuntimeError: undecidable comparison between 4W and 1M

======================================================================
ERROR: test_previous_next_reference_date (quantlib.test.test_schedule.ScheduleMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/pyql/quantlib/test/test_schedule.py", line 49, in setUp
    self.convention, self.termination_convention, self.rule
  File "quantlib/time/schedule.pyx", line 49, in quantlib.time.schedule.Schedule.__init__ (quantlib/time/schedule.cpp:1740)
    self._thisptr = new _schedule.Schedule(
RuntimeError: undecidable comparison between 4W and 1M

======================================================================
ERROR: test_size (quantlib.test.test_schedule.ScheduleMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/pyql/quantlib/test/test_schedule.py", line 49, in setUp
    self.convention, self.termination_convention, self.rule
  File "quantlib/time/schedule.pyx", line 49, in quantlib.time.schedule.Schedule.__init__ (quantlib/time/schedule.cpp:1740)
    self._thisptr = new _schedule.Schedule(
RuntimeError: undecidable comparison between 4W and 1M

----------------------------------------------------------------------
Ran 168 tests in 112.408s

FAILED (errors=5, skipped=1)
make: *** [tests] Error 1
```

**Comment by dpinte** [comment]
@Jakobovski The RuntimeError is a translation of a C++ exception. What version of Quantlib do you use?

**Comment by Jakobovski** [comment]
Thanks for the fast response. I reinstalled pyql and now all tests are passing. Another issue came up though :(.  I will close this issues and make a new one.
