### ISSUE TITLE
Test Failures on OS X

### ISSUE THREAD

**Issue by smallnamespace** [enthought/pyql#111]
Here are the errors I'm seeing:

```
======================================================================
ERROR: test_option_quotes (quantlib.test.test_notebooks.NoteBooksTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jianliu/git_projects/lendingclub-explore/src/pyql/quantlib/test/test_notebooks.py", line 162, in test_option_quotes
    option_data_frame = pandas.core.common.load(
AttributeError: module 'pandas.core.common' has no attribute 'load'

======================================================================
ERROR: test_at (quantlib.test.test_schedule.ScheduleMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jianliu/git_projects/lendingclub-explore/src/pyql/quantlib/test/test_schedule.py", line 49, in setUp
    self.convention, self.termination_convention, self.rule
  File "quantlib/time/schedule.pyx", line 49, in quantlib.time.schedule.Schedule.__init__ (quantlib/time/schedule.cpp:1742)
    self._thisptr = new _schedule.Schedule(
RuntimeError: undecidable comparison between 4W and 1M
======================================================================
ERROR: test_dates (quantlib.test.test_schedule.ScheduleMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jianliu/git_projects/lendingclub-explore/src/pyql/quantlib/test/test_schedule.py", line 49, in setUp
    self.convention, self.termination_convention, self.rule
  File "quantlib/time/schedule.pyx", line 49, in quantlib.time.schedule.Schedule.__init__ (quantlib/time/schedule.cpp:1742)
    self._thisptr = new _schedule.Schedule(
RuntimeError: undecidable comparison between 4W and 1M

======================================================================
ERROR: test_iter_dates (quantlib.test.test_schedule.ScheduleMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jianliu/git_projects/lendingclub-explore/src/pyql/quantlib/test/test_schedule.py", line 49, in setUp
    self.convention, self.termination_convention, self.rule
  File "quantlib/time/schedule.pyx", line 49, in quantlib.time.schedule.Schedule.__init__ (quantlib/time/schedule.cpp:1742)
    self._thisptr = new _schedule.Schedule(
RuntimeError: undecidable comparison between 4W and 1M

======================================================================
ERROR: test_previous_next_reference_date (quantlib.test.test_schedule.ScheduleMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jianliu/git_projects/lendingclub-explore/src/pyql/quantlib/test/test_schedule.py", line 49, in setUp
    self.convention, self.termination_convention, self.rule
  File "quantlib/time/schedule.pyx", line 49, in quantlib.time.schedule.Schedule.__init__ (quantlib/time/schedule.cpp:1742)
    self._thisptr = new _schedule.Schedule(
RuntimeError: undecidable comparison between 4W and 1M

======================================================================
ERROR: test_size (quantlib.test.test_schedule.ScheduleMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jianliu/git_projects/lendingclub-explore/src/pyql/quantlib/test/test_schedule.py", line 49, in setUp
    self.convention, self.termination_convention, self.rule
  File "quantlib/time/schedule.pyx", line 49, in quantlib.time.schedule.Schedule.__init__ (quantlib/time/schedule.cpp:1742)
    self._thisptr = new _schedule.Schedule(
RuntimeError: undecidable comparison between 4W and 1M

----------------------------------------------------------------------
```

The pandas issue seems to be because ```pandas.core.common.load``` was deprecated or removed in 0.17.

As for quantlib, I'm using a fresh build against quantlib HEAD as of today. Everything is compiled using clang against libstdc++ on El Capitan.

**Comment by dpinte** [comment]
What version of QL do you use? I suspect that is the issue with the RuntimeError.

**Comment by liujimj** [comment]
> As for quantlib, I'm using a fresh build against quantlib HEAD as of today

**Comment by smallnamespace** [comment]
> As for quantlib, I'm using a fresh build against quantlib HEAD as of today

Is HEAD not supported?

**Comment by dpinte** [comment]
@smallnamespace it seems it's not ;-) QL 1.4 without a doubt. I think that is what we use on Travis-CI. PR's are welcome to update to the latest releases. Looking at the errors, it should not be a big deal.

**Comment by smallnamespace** [comment]
@dpinte OK, thanks for clarifying. I might look into fixing the tests at some point -- right now am just getting started with using PyQL.

By the way, it might be worthwhile to update the docs, as they [currently](http://pyql.readthedocs.org/en/latest/getting_started.html#building-and-installing-pyql) clearly state that more recent versions are supported. Noting the last well-tested dependency versions might be helpful.

**Comment by dpinte** [comment]
@smallnamespace agreed. Will try to do it asap. There is a bit of cleanup that needs to be done on the doc, requirements, etc.

**Comment by smallnamespace** [comment]
@dpinte 
The errors in the schedule test seem genuine, filed with upstream at https://github.com/lballabio/QuantLib/issues/28
