### ISSUE TITLE
test_cds error

### ISSUE THREAD

**Issue by phenaff** [enthought/pyql#159]
This may be stale code... module enum no longer exists.
Python 2.7.3 / QuanLib 1.8 / Cython 0.24.1

======================================================================
ERROR: quantlib.test.test_cds (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: quantlib.test.test_cds
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/home/phn/dev/pyql/quantlib/test/test_cds.py", line 8, in <module>
    from quantlib.termstructures.credit.api import (
  File "/home/phn/dev/pyql/quantlib/termstructures/credit/api.py", line 2, in <module>
    from .piecewise_default_curve import PiecewiseDefaultCurve, ProbabilityTrait, Interpolator
  File "quantlib/termstructures/credit/piecewise_default_curve.pyx", line 21, in init quantlib.termstructures.credit.piecewise_default_curve (quantlib/termstructures/credit/piecewise_default_curve.cpp:6351)
    from enum import IntEnum
ImportError: No module named enum

**Comment by thrasibule** [comment]
Do you have enum34 installed? It should work fine with it. I have added it to requirements.txt as well, so pip should pull it as a dependency.

**Comment by phenaff** [comment]
My bad, thanks for the info, all is well (QuantLib 1.8 / Cython 0.24.1)
