### ISSUE TITLE
Numerical failures for 2 tests on win32

### ISSUE THREAD

**Issue by dpinte** [enthought/pyql#64]
Reported in #63 

```
======================================================================
FAIL: test_smith (quantlib.test.test_heston_model.HestonModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\dev\pyql\quantlib\test\test_heston_model.py", line 432, in test_smith
    delta=tolerance)
AssertionError: 15.244970794333526 != 15.1796 within 0.05 delta

======================================================================
FAIL: test_simulate_heston_2 (quantlib.test.test_simulate.SimTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\dev\pyql\quantlib\test\test_simulate.py", line 120, in test_simulate_heston_2
    self.assertAlmostEqual(res[1, -1], 152.50, delta=.1)
AssertionError: 153.26720068021842 != 152.5 within 0.1 delta

----------------------------------------------------------------------
Ran 144 tests in 15.095s

FAILED (failures=2, skipped=1)
```

**Comment by david-wolf** [comment]
I am seeing this on x64 as well.  This was opened in 2014 are there any plans to fix this?

**Comment by dpinte** [comment]
@david-wolf there are not short term plans but we would gladly accept patches!
